#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun -show drun -location 1 -xoffset 10 -yoffset 36 -line-padding 4 -columns 1 -width 20 -lines 10 -padding 25 -hide-scrollbar -show-icons -drun-icon-theme "Papirus"
