#!/bin/bash

## Created By Aditya Shakya

rofi -modi run,drun,window -lines 10 -padding 20 -width 50  -location 1 -yoffset 60 -xoffset 28 -show drun -sidebar-mode -columns 3 -font "Fantasque Sans Mono 10"
