#!/bin/bash

## Author : Aditya Shakya
## Github : adi1090x

# Custom Rofi Script

BORDER="#43413D"
SEPARATOR="#43413D"
FOREGROUND="#EAEAEA"
BACKGROUND="#43413D"
BACKGROUND_ALT="#43413D"
HIGHLIGHT_BACKGROUND="#393939"
HIGHLIGHT_FOREGROUND="#EAEAEA"

BLACK="#000000"
WHITE="#ffffff"
RED="#e53935"
GREEN="#43a047"
YELLOW="#fdd835"
BLUE="#1e88e5"
MAGENTA="#00897b"
CYAN="#00acc1"
PINK="#d81b60"
PURPLE="#8e24aa"
INDIGO="#3949ab"
TEAL="#00897b"
LIME="#c0ca33"
AMBER="#ffb300"
ORANGE="#fb8c00"
BROWN="#6d4c41"
GREY="#757575"
BLUE_GREY="#546e7a"
DEEP_PURPLE="#5e35b1"
DEEP_ORANGE="#f4511e"
LIGHT_BLUE="#039be5"
LIGHT_GREEN="#7cb342"


SDIR="$HOME/.config/polybar/scripts"

# Launch Rofi
MENU="$(rofi -no-lazy-grab -sep "|" -dmenu -i -p 'Style :' \
-hide-scrollbar true \
-bw 0 \
-lines 5 \
-line-padding 4 \
-padding 10 \
-width 15 \
-xoffset 0 -yoffset 26 \
-location 3 \
-columns 1 \
-show-icons -icon-theme "Papirus" \
-font "Noto Sans 9" \
-color-enabled true \
-color-window "$BACKGROUND,$BORDER,$SEPARATOR" \
-color-normal "$BACKGROUND_ALT,$FOREGROUND,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-active "$BACKGROUND,$MAGENTA,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
-color-urgent "$BACKGROUND,$YELLOW,$BACKGROUND_ALT,$HIGHLIGHT_BACKGROUND,$HIGHLIGHT_FOREGROUND" \
<<< "> Budgie|> Deepin|> Elementary_dark|> Elementary_light|> Gnome|> Kde|> Kde_alt|> Liri|> Mint|> Ubuntu_gnome|> Ubuntu_unity|> Xubuntu|> Zorin")"
            case "$MENU" in
				## Colors
				*Budgie) $SDIR/style -budgie ;;
				*Deepin) $SDIR/style -deepin ;;
				*Elementary_dark) $SDIR/style -elementary_dark ;;
				*Elementary_light) $SDIR/style -elementary_light ;;
				*Gnome) $SDIR/style -gnome ;;
				*Kde) $SDIR/style -kde ;;
				*Kde_alt) $SDIR/style -kde_alt ;;
				*Liri) $SDIR/style -liri ;;
				*Mint) $SDIR/style -mint ;;
				*Ubuntu_gnome) $SDIR/style -ubuntu_gnome ;;
				*Ubuntu_unity) $SDIR/style -ubuntu_unity ;;
				*Xubuntu) $SDIR/style -xubuntu ;;
				*Zorin) $SDIR/style -zorin ;;
            esac
